In [25]:
## Q1
x = float(input("Enter a number: ")) ## Taken float as input. Because number can be decimal number also
a = lambda x: x**2                   ## Condition   
print("Square of ",x,"is",square(x))

Enter a number:  3


Square of  3.0 is 9.0


In [1]:
## Q2
list(map(lambda x: x * 2, [1, 2, 3, 4, 5]))

[2, 4, 6, 8, 10]

In [2]:
## Q3
list(filter(lambda x:x%2==0,[10,15,20,25,30]))

[10, 20, 30]

In [7]:
## Q11

a = [5, 10, 15, 20]    ## Assigning the list first
s = 0                  ## Total = 0
for i in a:
    s+=i               ## Condition for totaling
    print("Total sum is: ",s)

Total sum is:  5
Total sum is:  15
Total sum is:  30
Total sum is:  50


In [13]:
## Q12

a = 6         ## Assiging a number
c = 1         ## Starting count stored in variable c

while c<=10:      ## condition for table till 10
    print(a*c)   
    c+=1          ## Count incremented by 1 till the condition is false

6
12
18
24
30
36
42
48
54
60


In [10]:
## Q14

a = 2                           ## Number assigned
if a%2==0:                       ## Condition
    print("It is an even number")
else:
    print("It is an odd number")

It is an even number


In [12]:
##Q15

marks = int(input("Enter marks: "))   ## User input

if marks>=90:                   ## Condition for grade A
    print("GRADE: A")
elif marks>=75:                 ## Condition for grade B
    print("GRADE: B")
elif marks>=50:                 ## Condition for grade c
    print("GRADE: C")
else:
    print("GRADE: F")           ##Prints F means fail if marks less than 50

Enter marks:  45


GRADE: F


In [3]:
## Q18

def find_largest(numbers):
    return max(numbers)

# Example usage
numbers = [1, 2, 3, 4, 5]
largest = find_largest(numbers)

print(f"The largest number is {largest}.")


The largest number is 5.


In [26]:
## Q8

class Animal:                  ## Base class Animal
    def speak(self):           
        print("I am an animal.")

class Dog(Animal):             ## Derived class Dog
    def speak(self):
        print("I am a dog.")

animal = Animal()              ## Create instances of the classes
dog = Dog()

# Call the speak method for both instances
animal.speak()  # Output: I am an animal.
dog.speak()     # Output: I am a dog.


I am an animal.
I am a dog.


In [27]:
## Q10

for num in range(1,11):      ## Condition for 1 to 10 
    print(num)

1
2
3
4
5
6
7
8
9
10


### Numpy Questions

In [36]:
## Q1

import numpy as np       ## Importing the library

arr = np.zeros([3,4])    ## creating an array shape = [Row, Columns]
print(arr)               ## Output

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
## Q2

import numpy as np       ## Importing the library

arr = np.zeros([2,5])    ## craeting array Shape = [Row, Column]
print(arr)               ## Output

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [40]:
## Q3

import numpy as np

matrix = np.arange(1,11).reshape(2,5)    ## arange() 1 to 10 reshape() matrix shape that is 3x3
print(matrix)                           ## Output

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [42]:
## Q6

import numpy as np

array = np.array([1, 4, 9, 16])   ## Creating an array
sqrt_array = np.sqrt(array)       ## Taking squareroot of the array

print(sqrt_array)                 ## Output

[1. 2. 3. 4.]


In [44]:
## Q8

import numpy as np

array = np.array([1, 5, 9, 3, 6])     ## Creating an array
minimum_num = np.min(array)           ## Taking minimu values of numbers
print(minimum_num)                    ## Output

1


In [45]:
## Q9

import numpy as np

array = np.array([1, 5, 9, 3, 6])     ## Creating an array
maximum_num = np.max(array)           ## Taking maximum value of numbers
print(maximum_num)  

9


In [46]:
## Q7

import numpy as np

array = np.array([2, 3, 4, 5, 6])
sum_numbers = np.sum(array)         ## Taking sum of the array
print(sum_numbers)

20


In [49]:
## Q10

import numpy as np

array = np.array([1.2, 2.5, 3.7, 4.9])
Round_off = np.ceil(array)            ## This method prints nearest value
print(Round_off)

[2. 3. 4. 5.]


In [51]:
## Q11

import numpy as np
random_integers = np.random.randint(10, 51, size=5)  ## The function mentioned prints random numbers from that range.
                                                      ## Size represents number of elements you want
print(random_integers)

[10 33 12 50 13]


In [53]:
## Q20

import numpy as np

array = np.array([10, 20, 30, 40, 50])
sliced_array = array[:2]                 ## Slicing the starting two elements

print(sliced_array)

[10 20]
