In [2]:
import numpy as np

In [3]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [5]:
np.sqrt(9)    ## Prints the square root of the element enetered

3.0

In [8]:
print("Minimum ",np.amin([23, 24, 25, 26]))  ##np.amin() prints minimum number from the list entered

Minimum  23


In [9]:
print("Maximum ",np.amax([89, 76, 65, 34]))  ##np.amax() prints maximum number from the list entered

Maximum  89


In [10]:
np.ceil(34.54)    ##np.ceil() function print round-off element enetered

35.0

In [12]:
np.ceil(np.sqrt(17))   ## first takes the square root and then prints its round-off figure

5.0

In [16]:
np.ceil(np.sum(np.sqrt([6,12,18])))   ## (1) First squareroot (2) Second sum of the elements (3) Round-off the element

11.0

In [17]:
np.array([23, 34, 45])   ## np.array() creates array

array([23, 34, 45])

In [18]:
type([23, 34, 45])

list

In [22]:
arr = np.array([23, 34, 45])    ## Assigned list as numpy.list
type(arr)                       ## This will print numpy.ndarray

numpy.ndarray

In [23]:
## Two dimensional array

In [25]:
a=np.array([[1,0,0],[0,1,0],[0,0,1]])  ## [[ indicates we are constructing two dimensional array
print("Type - ",a.dtype)               ## prints the data type of the element

print("\n",a)

Type -  int32

 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [27]:
np.array([5,8,9],dtype=float)   ## Converts the array dtype to float

array([5., 8., 9.])

In [28]:
list = [1, 2, 3, 4]
arr = np.array(list)        ## Converts list to an np.array
print(arr)

[1 2 3 4]


In [29]:
type(arr)

numpy.ndarray

In [30]:
arr2=np.asarray(arr)    ## np.asarray() copies the previous array as it is in the new array

In [31]:
print(arr2)

[1 2 3 4]


In [32]:
## Data Types in numpy

In [33]:
import numpy as np

In [35]:
my_mat=[[1,0,0],[0,1,0],[0,0,1]]
mat=np.array(my_mat)
print("Type/class of this object : ",type(mat))
print(mat) 
print("print dimension of this matrix : ",mat.ndim)#ndim gives dimension,2 for a matrix and 1 for vector
print("size of the matrix : ",mat.size)#size shows total number elements
print("Shape of the matrix : ",mat.shape)#shape shows how many rows and column
print("Data Type of the matrix ; ",mat.dtype)#shoes which type

Type/class of this object :  <class 'numpy.ndarray'>
[[1 0 0]
 [0 1 0]
 [0 0 1]]
print dimension of this matrix :  2
size of the matrix :  9
Shape of the matrix :  (3, 3)
Data Type of the matrix ;  int32


In [38]:
b = np.arange(20)     ## Prints the numbers till the 19

In [39]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
c = np.arange(10.8, 24.8, 3)  ## Range from 10.8 to 24.8 and with a stepsize of 3. Means print elements with a difference of 3

In [47]:
c

array([10.8, 13.8, 16.8, 19.8, 22.8])

In [48]:
## Reverse Order

In [50]:
print("Every 2nd number from 20 in reverse order \n",np.arange(20,-10,-2))

Every 2nd number from 20 in reverse order 
 [20 18 16 14 12 10  8  6  4  2  0 -2 -4 -6 -8]


In [53]:
print(np.linspace(22, 34, 6))   ## prints numbers from the range of 22 to 34. Total numbers 6

[22.  24.4 26.8 29.2 31.6 34. ]


In [55]:
np.linspace(8.0,18.0,num=4,endpoint=True,retstep=True)  ## Prints  from 8 to 18 with stepsize of 3.333 as shown in the output

(array([ 8.        , 11.33333333, 14.66666667, 18.        ]),
 3.3333333333333335)

In [56]:
## Matrix Creation

In [57]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [63]:
print(np.ones([5,6]))  ## 5 represents rows. 6 represent columns which is the matrix as shown

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [64]:
print(np.zeros([5]))

[0. 0. 0. 0. 0.]


In [65]:
print(np.zeros([5,6]))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [66]:
## Let us try for other numbers

In [67]:
print(8*np.ones([5,6]))

[[8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8.]]


In [68]:
## Construct Diagonal Matrix

In [70]:
x=np.arange(20).reshape(5,4)   ## Range till 20. And Shape of the matrix 5*4
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [71]:
## Random Number Generation

In [76]:
## Real Time Example

In [72]:
import numpy as np

In [77]:
def generate_otp():                             ## Created a function 
    otp=np.random.randint(1000,10000,1)         ## Random number between 1000 to 10000
    print("Your Otp is ",otp)                   ## Printing the OTP/ Random number
    user_otp=int(input("Enter Your OTP Here"))  ## Enter the random number displayed above 
    if otp==user_otp:                           ## Condition for successful login 
        print("Log in Sucessfully")
    else:                                       ## Else invalid 
        print("Your OTP is invalid")

In [78]:
generate_otp()

Your Otp is  [8193]


Enter Your OTP Here 8193


Log in Sucessfully


In [79]:
print("Random integer vector : ",np.random.randint(5,20,10))

Random integer vector :  [ 8  9 19  6 12  6 17  7 17  9]


In [84]:
import numpy as np

np.random.seed(42)     # Set the seed to 42    

print(np.random.rand(7, 6)) ## np.random.rand() generates random numbers from a uniform distribution Over the interval [0,1]
                            ## (7, 6) specifies matrix size (rows, Columns)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303 0.44015249 0.12203823 0.49517691]]
