In [1]:
import numpy as np

In [5]:
emp_salary = np.random.randint(23, 40, 10)

In [6]:
emp_salary

array([28, 29, 34, 36, 30, 28, 31, 35, 31, 36])

In [13]:
np.clip(emp_salary,a_min=24,a_max=35)    ## Clip() method here converts numbers into max and min values between 24 and 35

array([28, 29, 34, 35, 30, 28, 31, 35, 31, 35])

In [14]:
print(np.where(emp_salary >35))    ## Where() method heres finds out the employees having salary greater than 35

(array([3, 9], dtype=int64),)


In [16]:
emp_salary[[2,7]]   ## Prints numbers present at that index value

array([34, 35])

In [17]:
import numpy as np
from numpy.random import randint as ri

In [23]:
a=ri(1,50,16)      ## Takes random numbers between 1 to 50. Number of elements 15
print(a)

[49 17  6 43 27 20 32 37 23 34  3 39  7  9 36 10]


In [31]:
b=a.reshape(2,2,4)  ## Here there are 2 matrices. With shape of 2x4 
print(b)

[[[49 17  6 43]
  [27 20 32 37]]

 [[23 34  3 39]
  [ 7  9 36 10]]]


In [32]:
c=a.reshape(4,4)     ## Now combined the two matrices into one
print(c) 

[[49 17  6 43]
 [27 20 32 37]
 [23 34  3 39]
 [ 7  9 36 10]]


In [33]:
print("Minimum of a is ",c.min())
print("Maximum of a is ",c.max())

Minimum of a is  3
Maximum of a is  49


In [34]:
## Sorting

In [37]:
m=ri(1,50,20).reshape(4, 5) #matrix of random integer
print("\n 4 X 5 matrix of random integer \n",m)
print("\n Here is the sorted matrix along each row \n",np.sort(m))#default axis=1 used to sort numbers column wise
print("\n Here is the sorted matrix along each column \n",np.sort(m,axis=0))  ## axis=0 used to sort numbers column wise


 4 X 5 matrix of random integer 
 [[12 15 37 10  7]
 [ 5 29 30 11 45]
 [13 18 49 43 32]
 [ 8 33 16 20 35]]

 Here is the sorted matrix along each row 
 [[ 7 10 12 15 37]
 [ 5 11 29 30 45]
 [13 18 32 43 49]
 [ 8 16 20 33 35]]

 Here is the sorted matrix along each column 
 [[ 5 15 16 10  7]
 [ 8 18 30 11 32]
 [12 29 37 20 35]
 [13 33 49 43 45]]


In [38]:
## Indexing and slicing

In [39]:
arr = np.arange(12, 20)
print("Array", arr)

Array [12 13 14 15 16 17 18 19]


In [41]:
print(arr[5])    ## Prints the element at index 5

17


In [45]:
print(arr[0::2]) ## Prints numbers 1 to the end with a step size of 2 as you can see

[12 14 16 18]


In [47]:
print(arr[:6])  ## Prints elements till the index 5 element

[12 13 14 15 16 17]


In [57]:
print(arr[-1:-5:-1])  ## Prints numbers in reverse order from -1 to -5 at stopsize of -1

[19 18 17 16]


In [58]:
my_mat=[[1,0,0],[0,1,0],[0,0,1]]
mat=np.array(my_mat)
print(mat)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [62]:
print(mat[1])  ## Prints the Row matrix at index 1

[0 1 0]


In [64]:
print(mat[:,2:])   ## Prints the columns starting from index 2 to end which is only one column as shown

[[0]
 [0]
 [1]]


In [66]:
print(mat[1:3,1:3])   ## prints the [Row, Column] that are indexed as given

[[1 0]
 [0 1]]


In [69]:
print(mat[0:2, [0, 1]])  ## [Row, Column] Where Row = 0 to 2 and as given only 0 and 1 index columns will be printed

[[1 0]
 [0 1]]


In [70]:
## Updating a matrix

In [73]:
mat[1, 1] = 2     ## As you can see we updated the number at 1st row and 1st column

In [74]:
mat

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 1]])

In [75]:
mat=np.array(ri(50,100,25)).reshape(5,5)
print(mat)

[[60 99 83 97 56]
 [94 70 70 79 63]
 [70 55 81 83 93]
 [77 91 52 58 80]
 [74 98 67 94 98]]


In [78]:
print(mat[mat<60])  ## Prints numbers that are smaller than 60

[56 55 52 58]


In [80]:
print(np.where(mat==70))   ## where() function will here print the array dimensions where the element is present

(array([1, 1, 2], dtype=int64), array([1, 2, 0], dtype=int64))


In [81]:
## Above you can see 70 is present 3 times in the matrix
## One at the position [1,1]
## Second at position [1,2]
## Third at positiion [2,0]

In [83]:
age=55                                        ## You can also use Where() function to return some data at particular condition
np.where(age>60,'Retired','Still Working')

array('Still Working', dtype='<U13')

In [92]:
mat1=np.array(ri(1,20,8)).reshape(4,2)
mat2=np.array(ri(1,20,8)).reshape(4,2)

print(mat1)
print()
print(mat2)

[[ 6  1]
 [ 9  8]
 [ 3  4]
 [ 5 10]]

[[15  6]
 [18  6]
 [13  2]
 [11 13]]


In [94]:
print(mat1/mat2)    ## Division of two matrix 

[[0.4        0.16666667]
 [0.5        1.33333333]
 [0.23076923 2.        ]
 [0.45454545 0.76923077]]


In [106]:
print(4*mat1+2*mat2)   ## Linear combination of two matrix

[[54 16]
 [72 44]
 [38 20]
 [42 66]]


In [107]:
## Created one matrix on ones

In [102]:
a = np.ones((3,3))

In [103]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [104]:
b = np.array([2, 0, 2])

In [108]:
print(a+b)   ## Adding array b to matrix a

[[3. 1. 3.]
 [3. 1. 3.]
 [3. 1. 3.]]


In [117]:
c = np.array([[2,0,2]])   ## Two dimensional array

In [122]:
new_column=c.T  # T is use for transpose it convert column into row #vice versa

In [123]:
new_column

array([[2],
       [0],
       [2]])

In [124]:
d = new_column+a

In [125]:
d

array([[3., 3., 3.],
       [1., 1., 1.],
       [3., 3., 3.]])

In [127]:
print(np.sqrt(d))
print()
print(np.square(d))

[[1.73205081 1.73205081 1.73205081]
 [1.         1.         1.        ]
 [1.73205081 1.73205081 1.73205081]]

[[9. 9. 9.]
 [1. 1. 1.]
 [9. 9. 9.]]
